### ISSUE TITLE
Este repositório continua sendo mantido?

### ISSUE THREAD

**Issue by waghcwb** [dinhani/empresas-tecnologia-informacao#70]
Ao que parece faz algum tempo que os pull requests não estão sendo aceitos. @dinhani você continua mantendo esse repositório?

![](https://i.imgur.com/1FRDVXw.png)

**Comment by dinhani** [comment]
Continua. Eu não estava recebendo notificações das PRs no e-mail, por isso ficaram tanto tempo aí, mas já atualizei para receber e também dei merge nelas.

**Comment by waghcwb** [comment]
Obrigado pela resposta, perguntei pois queria abrir o #71
